name: pytest

on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: build poetry env 
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        #action/setup-python에서 ${{matrix.python-version}} 을 하면 3.1로 인식되는 버그가 있음
        python-version: ["3.10"]
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        
      - name: Setup python3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH 
        
      - name: Install dependencies
        run: poetry install --no-interaction
        
      - name: Check style
        run: poetry run black .
        #continue-on-error: true면 check style이 실패해도 계속 진행됨
      
      - name: Check types
        run: poetry run mypy
          
      - name: Run test
        run: poetry run pytest --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml 
        
      - name: Upload pytest test result
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml  
          #보존기간 정의
          retention-days: 1
        #테스트가 실패해도 항상 Upload pytest test result를 실행함
        if: ${{ always() }}
