name: pytest

on:
  push:
    branches: [main]
    paths-ignore: 
      - '**.md'
  
  pull_request:
    branches: [main, develop]
    paths-ignore: '**.md'

jobs:
  #스타일 체크
  style:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install --no-interaction --only style
      - name: Check style with black
        run: poetry run black --check .
      - name: Check style with isort
        run: poetry run isort --check .
        
  # 타입체크
  type:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install --no-interaction --only type
      - name: Check type
        run: poetry run mypy
  
  #pytest 
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install --no-interaction --only test
      - name: Check test
        run: poetry run pytest 
        
        
        
  build:
    name: build and upload
    runs-on: ${{ matrix.os }}
    needs: [style, type, test]
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        #action/setup-python에서 ${{matrix.python-version}} 을 하면 3.1로 인식되는 버그가 있음
        python-version: ["3.10"]
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH 
      - name: Install dependencies
        #--only-root 해도 괜찮은가?
        run: poetry install --no-interaction
      - name: Build whl file
        run: poetry build
      - name: Upload whl file
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/*.whl
      #    #보존기간 정의
          retention-days: 1
