name: pytest

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - develop

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.10]
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: setup python3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: install poetry
        run: |
          pip install poetry
      
      - name: add path for poetry
        run: |
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      
      - name: install dependencies
        run:
          poetry install --no-interaction
          
      - name: check style
        run: poetry run black .
      
      - name: check types
        run: poetry run mypy
          
      - name: run test
        run: poetry run pytest
        
