name: pytest

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - develop

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.10]
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: setup python ${{ matrix.python-version }}
        uses: action/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: install poetry
        run: |
          pip install poetry
      
      - name: add path for poetry
        run: |
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      
      - name: install dependencies
        run:
          poetry install --no-interaction
          
      - name: run test
        run: |
          poetry run pytest test
        
